# -*- coding: utf-8 -*-
"""EDFxYXIR_technical_test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMKhGhEna05isQROQRC_LooDJTCWecyz
"""

!pip install mteb

!pip install torch torchvision torchaudio

import numpy as np
import json
import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt
from mteb import MTEB
from sentence_transformers import SentenceTransformer, util
import torch
from sentence_transformers import InputExample
from sklearn.model_selection import train_test_split

from torch.utils.data import DataLoader
from sentence_transformers import losses
from sklearn.metrics.pairwise import cosine_similarity

from sklearn.metrics import classification_report
import os
import datetime
from sentence_transformers.evaluation import TripletEvaluator

from transformers import T5ForConditionalGeneration, T5Tokenizer
import re

from tqdm import tqdm

# !nvidia-smi

print(torch.cuda.is_available())

from google.colab import drive
drive.mount('/content/drive')

data_file= "/content/drive/MyDrive/YXIR/dataset_big_patent_v3.json"
with open(data_file , "r", encoding="utf-8") as f:
    data = json.load(f)
# data

df = pd.DataFrame(data)

df.columns

df['anchor_len'] = df['anchor'].apply(lambda x: len(x.split()))
df['query_len'] = df['query'].apply(lambda x: len(x.split()))
df['pos_len'] = df['positive'].apply(lambda x: len(x.split()))
df['neg_len'] = df['negative'].apply(lambda x: len(x.split()))

print(df[['anchor_len', 'query_len', 'pos_len', 'neg_len']].mean())

df[['anchor_len', 'query_len', 'pos_len', 'neg_len']].hist(bins=30, figsize=(12, 8))
plt.suptitle("Distribution of Token Counts")
plt.show()

"""### Data preprocessing .."""

# def clean_ocr_noise(text):
#     text = text.encode().decode('unicode_escape')
#     text = re.sub(r'\n+', ' ', text)
#     return text.strip()

def clean_ocr_noise(text):
    # Replace double newlines with ". " to preserve sentence boundaries
    text = re.sub(r'\n+', '. ', text)
    # Keep Unicode symbols (e.g., \u2248 → ≈) but ensure they’re decoded
    text = text.encode().decode('unicode_escape')
    return text.strip()

text = "fr \u2248 1 2 \u2062 L \n\n E eff"
cleaned_text = clean_ocr_noise(text)
print(cleaned_text)

model = SentenceTransformer("intfloat/e5-base-v2")

raw_text = "fr \u2248 1 2 \u2062 L \n\n E eff"
cleaned_text = clean_ocr_noise(raw_text)

raw_emb = model.encode(raw_text)
cleaned_emb = model.encode(cleaned_text)


similarity = util.cos_sim(raw_emb, cleaned_emb).item()
print(f"Similarity between raw and cleaned: {similarity:.3f}")

related_text = "fr around 1 2..L E eff"
related_emb = model.encode(related_text)
raw_sim = util.cos_sim(raw_emb, related_emb).item()
cleaned_sim = util.cos_sim(cleaned_emb, related_emb).item()
print(f"Raw vs. related: {raw_sim:.3f}, Cleaned vs. related: {cleaned_sim:.3f}")

"""&rarr; maybe we skip on preprocessing for instance"""

#attempt on dissecting the anchor text ...

def section_anchor(anchor):
    # find potential all-caps headers
    pattern = r'\b[A-Z\s\-]+(?=\s*\[\d+\]|\s+[A-Za-z0-9])'
    headers = re.findall(pattern, anchor)

    # filter headers: must be at least 10 chars..
    headers = [header.strip() for header in headers if len(header) >= 10]

    if not headers:
        return {"FULL_TEXT": anchor.strip()}

    # create pattern to split on headers
    split_pattern = r'\b(?:' + '|'.join(map(re.escape, headers)) + r')\b'

    # split the text based on headers
    sections = re.split(split_pattern, anchor)

    # pair headers with their sections
    section_dict = {}
    for i, header in enumerate(headers):
        section_text = sections[i + 1].strip() if i + 1 < len(sections) else ""
        if section_text:
            section_dict[header] = section_text

    return section_dict

anchor = df.iloc[1]['anchor']

anchor

sectioned_anchor = section_anchor(anchor)

print(list(sectioned_anchor.keys()))
for header, text in sectioned_anchor.items():
    print(f"{header}:\n{text}\n")

sectioned_data = [section_anchor(anchor) for anchor in df['anchor']]

sectioned_df = pd.DataFrame(sectioned_data)

sectioned_df

for header in sectioned_df.columns:
    print(header)

"""&rarr; maybe DISCARD:


* Procedural/legal sections ( RELATED APPLICATIONS, PRIORITY CLAIMS)
* Metadata or references ( REFERENCE NUMBER, CROSS-REFERENCES)
* Non-descriptive or overly specific (CO-Q-Q-R-F-E-W-E-F-E-Q-Q-NH, LOT NO FORMULATION PH).
* Figures/drawings ( BRIEF DESCRIPTION OF THE DRAWINGS) unless we need visual context

### Approach 1 : Augment anchor with query
"""

# def truncate_text(text, max_tokens=450):
#     tokens = tokenizer(text, truncation=True, max_length=max_tokens, return_tensors="pt")
#     return tokenizer.decode(tokens["input_ids"][0], skip_special_tokens=True)

def augment_anchor(query, anchor, separator=" "):
    return f"{query}{separator}{anchor}"


augmented_data = []

for idx, row in df.iterrows():
    augmented_anchor = augment_anchor(row["query"], row["anchor"])
    augmented_data.append({
        "augmented_anchor": augmented_anchor,
        "positive": row["positive"],
        "negative": row["negative"]
    })

augmented_df = pd.DataFrame(augmented_data)

augmented_df.iloc[1]['augmented_anchor']

train_df, test_df = train_test_split(augmented_df, test_size=0.2, random_state=42)

"""####zero shot peformances results using some EMs

The evaluator calls the models encode that tokenize (via its tokenizer) then genrate embedding uses a binary classification metric to assess the models performance on the triplet task:

accuracy = (number of triplets where sim(anchor, positive) > sim(anchor, negative)) / (total number of triplets)
"""

model = SentenceTransformer("intfloat/e5-base-v2")

evaluator = TripletEvaluator(


    anchors = test_df["augmented_anchor"].tolist(),
    positives=test_df["positive"].tolist(),
    negatives=test_df["negative"].tolist(),
    similarity_fn_names=["cosine", "dot", "euclidean", "manhattan"],

    main_similarity_function= None, #tests on all

    show_progress_bar=True,
    write_csv=True


)

results = evaluator(model)

results

"""#### fine tuning peformances results using some EMs"""

train_examples = []
for idx, row in train_df.iterrows():
    train_examples.append(InputExample(
        texts=[row["augmented_anchor"], row["positive"], row["negative"]]
    ))

batch_size = 16
train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=batch_size)

# model = SentenceTransformer('intfloat/e5-base-v2')

print("Model:", model._first_module().__class__.__name__)

print("\nModel config:")
print(model._first_module().auto_model.config)
print("\nPooling type:")
print(model[1])

sample_embedding = model.encode(["test sentence"])
print("\nEmbedding dimension:", sample_embedding.shape[1])

triplet_loss = losses.TripletLoss(
     model=model,
    distance_metric=losses.SiameseDistanceMetric.COSINE_DISTANCE,
     triplet_margin = 0.1
   )

# torch.cuda.empty_cache()

num_epochs = 10
warmup_steps = int(len(train_dataloader) * 0.1)

model.fit(
    train_objectives=[(train_dataloader, triplet_loss)],
    epochs=num_epochs,
    warmup_steps=warmup_steps,
    show_progress_bar=True
)

"""time:"""

evaluator = TripletEvaluator(
    anchors = test_df["augmented_anchor"].tolist(),
    positives=test_df["positive"].tolist(),
    negatives=test_df["negative"].tolist(),

    # margin=margin,
    show_progress_bar=True


)

results = evaluator(model)

results

contrastive_loss = losses.ContrastiveLoss(
    model=model,
    distance_metric=losses.SiameseDistanceMetric.COSINE_DISTANCE,
    margin=0.5
)

train_samples = []
for _, row in test_df.iterrows():
    anchor = row["augmented_anchor"]
    positive = row["positive"]
    negative = row["negative"]
    # (QA, P)
    train_samples.append(InputExample(texts=[anchor, positive], label=1))
    # (QA, N)
    train_samples.append(InputExample(texts=[anchor, negative], label=0))

train_dataloader = DataLoader(train_samples, shuffle=True, batch_size=16)

model.fit(
    train_objectives=[(train_dataloader, contrastive_loss)],
    epochs=num_epochs,
    warmup_steps=warmup_steps,
    show_progress_bar=True
)

evaluator = TripletEvaluator(


    anchors = test_df["augmented_anchor"].tolist(),
    positives=test_df["positive"].tolist(),
    negatives=test_df["negative"].tolist(),

)

evaluator(model)

anchor = test_df["augmented_anchor"].iloc[7]
positive = test_df["positive"].iloc[7]
negative = test_df["negative"].iloc[7]

anchor_emb = model.encode(anchor, convert_to_tensor=True)
positive_emb = model.encode(positive, convert_to_tensor=True)
negative_emb = model.encode(negative, convert_to_tensor=True)

# Compute cosine similarities
pos_similarity = util.cos_sim(anchor_emb, positive_emb).item()
neg_similarity = util.cos_sim(anchor_emb, negative_emb).item()

# Compute cosine distances (1 - similarity)
pos_distance = 1 - pos_similarity
neg_distance = 1 - neg_similarity

print(f"Cosine Sim (Anchor, Positive): {pos_similarity:.4f}")
print(f"Cosine Sim (Anchor, Negative): {neg_similarity:.4f}")
print(f"Cosine Dist (Anchor, Positive): {pos_distance:.4f}")
print(f"Cosine Dist (Anchor, Negative): {neg_distance:.4f}")
print(f"Positive pair is closer: {pos_distance < neg_distance}")

# Prepare only positive pairs
train_samples = []
for anchor, positive, _ in zip(train_df["augmented_anchor"], train_df["positive"], train_df["negative"]):
    train_samples.append(InputExample(texts=[anchor, positive]))

train_dataloader = DataLoader(train_samples, shuffle=True, batch_size=16)

# Define MNRL
mnrl_loss = losses.MultipleNegativesRankingLoss(model=model)

# Fine-tune
model.fit(
    train_objectives=[(train_dataloader, mnrl_loss)],
    epochs=num_epochs,
    warmup_steps=warmup_steps,
    show_progress_bar=True
)

evaluator = TripletEvaluator(

    anchors = test_df["augmented_anchor"].tolist(),
    positives=test_df["positive"].tolist(),
    negatives=test_df["negative"].tolist(),

)

evaluator(model)

from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
import umap
import numpy as np



embeddings = []
labels = []

for _, row in test_df.iterrows():
    anchor = row["augmented_anchor"]
    positive = row["positive"]
    negative = row["negative"]

    emb_anchor = model.encode(anchor)
    emb_positive = model.encode(positive)
    emb_negative = model.encode(negative)

    embeddings.extend([emb_anchor, emb_positive, emb_negative])
    labels.extend(["Anchor", "Positive", "Negative"])


embeddings = np.array(embeddings)


reducer = umap.UMAP(n_components=2, random_state=42)
reduced = reducer.fit_transform(embeddings)

import seaborn as sns
plt.figure(figsize=(10, 6))
sns.scatterplot(x=reduced[:, 0], y=reduced[:, 1], hue=labels, palette="Set2", s=80)
plt.title("Embedding Space Visualization (UMAP)")
plt.legend(loc='best')
plt.tight_layout()
plt.show()

